server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d7ifeh1f9bms7384rli0-a.singapore-postgres.render.com/acadchain_db
spring.datasource.username=acadchain_db_user
spring.datasource.password=azBOIdzTlAoa56PNsGukVxzWP19z0Kx1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

server.servlet.session.timeout=30m
spring.application.name=AcadChain